polycube-network/polycube

- Documentation/quickstart.rst
docker login needs to be removed
> remove the shared login credential

- src/services/pcn-iptables/src/Chain.cpp
- src/services/pcn-iptables/test/local_test_horus1.sh
when all rules are removed, and HOURS is enabled, parser reloading is needed.
> pcn-iptables: fix HORUS when all rules are removed

- src/polycubed/src/rest_server.h
> polycubed: remove methods declaration in rest server

- README.md
We don't have a contributing guide yet, so remove this broken link.
> Remove broken link in main readme

- Documentation/installation.rst
- scripts/install.sh
- src/polycubed/src/CMakeLists.txt
- src/polycubed/src/rest_server.cpp
- src/polycubed/src/rest_server.h
SSL support has been merged into upstream pistache, switch to that version.
> polycubed: switch to upstream version of pistache

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This is in process of making the repo more organized and documented and easy to navigate.
So please provide your feedback. Thanks!
> Bug and Feature Request template

- src/components/iptables/scripts/pcn-iptables-clean
- src/components/iptables/scripts/pcn-iptables-init
- src/components/iptables/scripts/pcn-iptables-init-xdp
this PR improve output and messagges provided by
pcn-iptables-init
pcn-iptables-init-xdp
pcn-iptables-clean
> pcn-iptables: improve scripts output

- Documentation/cubes.rst
This PR purpose is to improve `cubes` section, under `Documentation`
> Documentation: improve cubes section

- scripts/install.sh
- src/polycubectl/CMakeLists.txt
- src/polycubectl/completion/polycubectl.sh
- src/polycubed/src/cube.cpp
- src/polycubed/src/cube.h
- src/polycubed/src/polycubed_core.cpp
- src/polycubed/src/polycubed_core.h
- src/polycubed/src/rest_server.cpp
- src/polycubed/src/rest_server.h
- src/polycubed/src/server/Parser/YangNodes.tcpp
- src/polycubed/src/server/Resources/Data/AbstractFactory.h
- src/polycubed/src/server/Resources/Data/BaseModel/ConcreteFactory.cpp
- src/polycubed/src/server/Resources/Data/BaseModel/ConcreteFactory.h
- src/polycubed/src/server/Resources/Data/BaseModel/LeafResource.cpp
- src/polycubed/src/server/Resources/Data/BaseModel/LeafResource.h
- src/polycubed/src/server/Resources/Data/Lib/ConcreteFactory.cpp
- src/polycubed/src/server/Resources/Data/Lib/ConcreteFactory.h
- src/polycubed/src/server/Resources/Data/Lib/LeafResource.cpp
- src/polycubed/src/server/Resources/Data/Lib/LeafResource.h
- src/polycubed/src/server/Resources/Endpoint/LeafListResource.cpp
- src/polycubed/src/server/Resources/Endpoint/LeafResource.cpp
- src/polycubed/src/server/Resources/Endpoint/LeafResource.h
- src/polycubed/src/server/Resources/Endpoint/ListResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ListResource.h
- src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ParentResource.h
- src/polycubed/src/server/Resources/Endpoint/Service.cpp
- src/polycubed/src/server/Resources/Endpoint/Service.h
- src/polycubed/src/server/Validators/EnumValidator.cpp
- src/polycubed/src/server/Validators/EnumValidator.h
Implement bash completion for polycubectl.
> implement bash autocompletion

- scripts/install.sh
add missing package to install.sh script.
> fix docker image building

- src/polycubed/src/server/Resources/Body/ListResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ListResource.h
- src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
- src/polycubed/src/server/Types/lexical_cast.cpp
- src/polycubed/src/server/Types/lexical_cast.h
fix still existing problems with list validation.
> polycubed: further fix to list validation

- src/libs/polycube/CMakeLists.txt
- src/libs/polycube/include/polycube/common.h
- src/libs/polycube/include/polycube/services/base_cube.h
- src/libs/polycube/include/polycube/services/cube.h
- src/libs/polycube/libpolycube.pc.in
- src/libs/spdlog/CMakeLists.txt
- src/services/CMakeLists.txt
- src/services/pcn-helloworld/src/CMakeLists.txt
Create pkg-config file for libpolycube.
solve: https://github.com/polycube-network/polycube/issues/91
> libpolycube: provide pkg-config

- Documentation/services/pcn-firewall/firewall.rst
pcn-firewall is now transparent, update documentation to reflect it
> pcn-firewall: update documents to transparent cube

- src/services/pcn-iptables/src/Chain.cpp
- src/services/pcn-iptables/src/ChainRule.cpp
> pcn-iptables: minor fixes

- src/services/pcn-simplebridge/datamodel/simplebridge.yang
- src/services/pcn-simplebridge/src/Ports.cpp
- src/services/pcn-simplebridge/src/Ports.h
- src/services/pcn-simplebridge/src/api/SimplebridgeApi.cpp
- src/services/pcn-simplebridge/src/api/SimplebridgeApi.h
- src/services/pcn-simplebridge/src/api/SimplebridgeApiImpl.cpp
- src/services/pcn-simplebridge/src/api/SimplebridgeApiImpl.h
- src/services/pcn-simplebridge/src/base/PortsBase.cpp
- src/services/pcn-simplebridge/src/base/PortsBase.h
- src/services/pcn-simplebridge/src/serializer/PortsJsonObject.cpp
- src/services/pcn-simplebridge/src/serializer/PortsJsonObject.h
MAC is not used anywhere, remove it.
> pcn-simplebridge: remove mac from ports

- src/polycubectl/cliargs/cliargs.go
After 074ece5b349a ("polycubectl: add reading from standard input capability")
polycubectl tries to read the standard input in all the invocations, this
causes commands typed by the user to hang up.
This commit uses a logic to detect if the standard input is being piped, in
that case it is used.
> polycubectl: fix reading from standard input

- Documentation/installation.rst
- scripts/install.sh
Dependencies in the installation guide were not aligned with the ones in
scripts/install.sh.
Solves: #143
> Documentation: update list of dependencies

- src/polycubed/src/service_controller.cpp
All the logic to allow to connect a cube's port and attach a transparent cube
to a netdev is inplace, before this commit it was possible to connect a port
to a netdev and then attach a transparent cube to the netdev, however the
inverse procedure, first attach and then connect was not working.
case working before:
- polycubectl router add r0
- polycubectl r0 ports add p1 ip=192.168.1.1 netmask=255.255.255.0
- polycubectl connect r0:p1 veth1
- polycubectl nat add nat0
- polycubectl attach nat0 veth1
case fixed by this commit:
- polycubectl nat add nat0
- polycubectl attach nat0 veth1
- polycubectl router add r0
- polycubectl r0 ports add p1 ip=192.168.1.1 netmask=255.255.255.0
- polycubectl connect r0:p1 veth1
> polycubed: fix connect after attach to netdev

- Dockerfile
- scripts/install.sh
Install golang from repo instead of downloading binary tar
> use golang from repo

- src/polycubectl/cliargs/cliargs.go
- src/polycubectl/completion/polycubectl.sh
- src/polycubed/src/port.cpp
- src/polycubed/src/port.h
- src/polycubed/src/server/Resources/Endpoint/ListResource.cpp
- src/polycubed/src/server/Resources/Endpoint/PathParamField.cpp
- src/polycubed/src/utils/netlink.h
- src/polycubed/src/utils/utils.cpp
- src/polycubed/src/utils/utils.h
- src/services/pcn-router/src/Ports.cpp
Fixes https://github.com/polycube-network/polycube/issues/27.
Merge only after https://github.com/polycube-network/polycube/pull/171 is merged.
> add url enconding

- scripts/install.sh
The main purpose of this PR is to modify the install script to avoiding the installation process to be blocked because the user is prompted for an option. This is causing issues in jenkins because tests are blocked.
> cleanup install

- Documentation/polycubed/polycubed.rst
- Documentation/quickstart.rst
- src/polycubed/CMakeLists.txt
- src/polycubed/systemdservice/CMakeLists.txt
- src/polycubed/systemdservice/polycubed.service.in
This commit provides an easy way to manage polycubed by using systemd.
> polycubed: provide systemd integration

- scripts/install.sh
If this script is launched on an existing (and perhaps old) source code repository, submodules may be out of date.
This commits adds a command that updates all the polycube submodules.
Signed-off-by: Fulvio Risso <fulvio.risso@polito.it>
> Updating submodules in the polycube repository

- scripts/install.sh
Jenkins cannot run git commands; it fixes a bug introduced with PR #181.
Signed-off-by: Fulvio Risso <fulvio.risso@polito.it>
> Fixes a bug in the Jenkins pipeline

- Documentation/components/k8s/developers.rst
- Documentation/components/k8s/pcn-kubernetes.rst
export pcn-k8s networking policy related document to the user
> add networking policy document link

- Documentation/components/k8s/pcn-kubernetes.rst
- Documentation/services/index.rst
- Documentation/services/pcn-bridge/example1/example1.rst
- Documentation/services/pcn-bridge/example2/example2.rst
- Documentation/services/pcn-bridge/example3/example3.rst
- Documentation/services/pcn-packetcapture/packetcapture.rst
- Documentation/services/pcn-pbforwarder/pbforwarder.rst
- src/services/pcn-packetcapture/src/Packetcapture.cpp
- src/services/pcn-pbforwarder/src/Pbforwarder_dp_parsing.c
packetcapture documentation added to the index file and solved some minor warnings
> Documentation updated

- Documentation/installation.rst
Added warning llvm 6 in install documentation
> Added warning llvm 6 in install documentation

- scripts/pre-requirements.sh
- add libpcre3-dev package that needed by compiling libyang
- install the package before compiling libyang source package
> add required package to make install script happy 

- Documentation/tutorials/index.rst
- Documentation/tutorials/tutorial4/tutorial4.rst
The aim of this commit is to provide simple but straightforward
documentation concerning the possibility to attach multiple transparent
cubes to the same interface.
> Documentation - Attach multiple transparent cubes

- Documentation/installation.rst
- scripts/pre-requirements.sh
This commit aims to improve the install script supporting also newest Ubuntu releases (> 20.04).
Issue related: #297
> Modified golang-go dependency to support Ubuntu 20.04

- Documentation/installation.rst
Since we landed to Ubuntu 20.04, I though that a bit more specifics could be added into the guide
> Improving Polycube doc - Install/Update kernel process

- Documentation/README.md
- Documentation/developers/dataplane.rst
- Documentation/installation.rst
- Documentation/intro.rst
- Documentation/polycubectl/polycubectl.rst
- Documentation/quickstart.rst
- Documentation/security.rst
- Documentation/services/index.rst
- Documentation/services/pcn-dynmon/dynmon.rst
- Documentation/services/pcn-packetcapture/packetcapture.rst
- Documentation/tutorials/tutorial4/tutorial4.rst
Added info for downloading Polycube release
Improved documentation in multiple files (mainly typos)
> Added info for downloading Polycube release

- .github/workflows/rebase.yml
* created a token with the `polycube-bot` 
* inserted token into `polycube-network/polycube` as `secrets`
* created `rebase.yml`
After the merge, it should be possible to comment `/rebase` in PR to automatically rebase the code
@palexster I would thank you if you could confirm that everything is ok (I checked our workflow in CrownLabs)
> add workflow to rebase code with polycube-bot

- src/services/pcn-dynmon/src/Dynmon.cpp
- src/services/pcn-dynmon/src/extractor/MapExtractor.cpp
> fix Dynmon empty-on-read percpu

- Documentation/services/pcn-nat/nat.rst
- src/services/pcn-nat/src/IpAddr.h
- src/services/pcn-nat/src/Rule.cpp
- src/services/pcn-nat/src/RuleDnat.cpp
- src/services/pcn-nat/src/RulePortForwarding.cpp
- src/services/pcn-nat/src/RuleSnat.cpp
This PR fixes two NAT bugs and corrects the documentation.
Details in commit messages.
Fixes #345.
> Fix NAT bugs

- Documentation/services/pcn-dynmon/dynmon.rst
- src/services/pcn-dynmon/src/Dynmon.cpp
- src/services/pcn-dynmon/src/swap/CodeRewriter.cpp
- src/services/pcn-dynmon/src/swap/CodeRewriter.h
- src/services/pcn-dynmon/src/swap/SwapStateConfig.cpp
> changed CodeRewriter enumeration names

- Documentation/services/pcn-dynmon/dynmon.rst
- src/services/pcn-firewall/ignore-tests/conntrack/test_tcp_complete_1.sh
Need to be merged after Simone's PR on Nov 2020.
> Updated with latest Simone's patches

- src/services/pcn-loadbalancer-rp/src/Lbrp.cpp
This PR fix the addService function. Now services are created correctly
> lbrp addService fix

- src/polycubed/src/controller.cpp
- Update BCC to v0.20.0.
- Replace the rcu lock with a spin lock in the code reading packets injected by the slow path into the fast path (the lock guarantees that multiple threads reading packets from the single ring do not incur in race conditions). Kernels >= 5.10 do not accept the rcu lock, and it probably wasn't effective anyway.
> Fix compatibility issues with kernel >= 5.10

- Documentation/developers/debugging.rst
This PR tries to provide a little guide to debug Polycube, using VS Code or CLion as IDE and tries to solve issue  #255 
Even though I've tried it several times, can anyone take a look? Thank you!
@frisso @FedeParola 
Comments on how to improve or modify it are welcome.
> doc to debug with VS Code and CLion (possible solution to #255)

- Documentation/developers/debugging.rst
- src/polycubed/src/datapath_log.cpp
- src/polycubed/src/datapath_log.h
This PR completes the work of removing pcn_pkt_log() references from code and documentation, resolving #234
> Solved issue #234

- scripts/install.sh
Polycube doesn't work if started with "&", at least the first time this is done after booting up.
Much better to use the "-d" flag.
> Update the polycubed starting string

- src/services/pcn-loadbalancer-rp/src/Service.cpp
- src/services/pcn-loadbalancer-rp/src/Service.h
- src/services/pcn-loadbalancer-rp/src/api/LbrpApiImpl.cpp
- src/services/pcn-loadbalancer-rp/src/interface/ServiceInterface.h
Hi! Since the lbrp service backends list replacement functionality was not implemented, I created a simple implementation of it. Hope it sounds good to you!
> implemented lbrp service backends replacing functionality

- src/services/pcn-nat/src/Nat_dp_egress.c
Turns out the problem with the NAT was simple (even if it took me quite some time to figure it out).
The NAT uses rcu_read_lock/unlock to concurrently increment the first free port used in SNAT and MASQ. These functions however are no longer accepted in newer kernels (and they probably weren't effective anyway) as in #384. I replaced them with a spin lock.
> Replace rcu_read_lock/unlock with spin locks in NAT data plane
