- src/services/pcn-k8switch/src/K8switch_dp.c
Remove two garbage lines that are breaking pcn-k8s.
> pcn-k8switch: remove garbage in datapath file

- src/components/k8s/dockersecret.yaml
- src/components/k8s/pcn-k8s.yaml
Docker images are now public hence dockersecret is not needed anymore.
> components/k8s: remove dockersecret

- src/services/pcn-iptables/src/CMakeLists.txt
- src/services/pcn-iptables/src/Chain.cpp
- src/services/pcn-iptables/src/Chain.h
- src/services/pcn-iptables/src/ChainStats.cpp
- src/services/pcn-iptables/src/Iptables.h
- src/services/pcn-iptables/src/Utils.cpp
- src/services/pcn-iptables/src/datapaths/Iptables_Horus_dp.c
- src/services/pcn-iptables/src/datapaths/Iptables_Parser_dp.c
- src/services/pcn-iptables/src/defines.h
- src/services/pcn-iptables/src/modules/Horus.cpp
- src/services/pcn-iptables/src/modules/Parser.cpp
this commit removes old references to ddos mitigator, that was the original name of the module used to implement HORUS optimization.
> pcn-iptables: cleanup old references to DDoS in HORUS

- src/libs/polycube/include/polycube/services/cube.h
this commit improves error message when trying to access invalid port, by throwing an exception with a clear message.
> improve get_port() error message if no port present

- src/services/pcn-iptables/src/CMakeLists.txt
- src/services/pcn-iptables/src/Chain.cpp
- src/services/pcn-iptables/src/Chain.h
- src/services/pcn-iptables/src/ChainRule.cpp
- src/services/pcn-iptables/src/ChainRule.h
- src/services/pcn-iptables/src/Iptables.cpp
- src/services/pcn-iptables/src/Iptables.h
- src/services/pcn-iptables/src/Utils.cpp
- src/services/pcn-iptables/src/datapaths/Iptables_InterfaceLookup_dp.c
- src/services/pcn-iptables/src/defines.h
- src/services/pcn-iptables/src/modules/InterfaceLookup.cpp
- src/services/pcn-iptables/test/local_test_interfaces1.sh
Please don't merge until https://github.com/polycube-network/iptables/pull/1 is merged.
After that, we can update submodule reference in this PR.
this commit introduces support for filtering packets on interfaces.
e.g.
pcn-iptables -A INPUT -i eth0 -d 10.0.0.1 -j DROP
pcn-iptables -A OUTPUT -o eth1 -j DROP
pcn-iptables -A FORWARD -i veth1 -j ACCEPT
limitations:
- on FORWARD chain only support for -i parameter.
Due to architecture of pcn-iptables, support -o parameter would require
to guess linux routing decision in INGRESS hook, or to extend EGRESS hook
to filter also packets already processed by FORWARD pipeline.
> pcn-iptables: implement support for interface filtering (-i -o options)

- src/services/pcn-simplebridge/src/FdbEntry.cpp
- src/services/pcn-simplebridge/src/FdbEntry.h
- src/services/pcn-simplebridge/src/Simplebridge.cpp
- src/services/pcn-simplebridge/src/Simplebridge.h
- src/services/pcn-simplebridge/src/Simplebridge_dp.c
This PR introduces a huge performance increase in the `Simplebridge` service by removing some bottlenecks from the data path such as the call to the `bpf_ktime_get_ns` and the `bpf_map_update` used to update the timestamp.
In fact, after some tests, I discovered that this function introduces a huge performance degradation (more evident in the multi-core tests due the lock required by the update) while updating the value directly after the lookup does not impact on the overall performance.
With this commit, the multicore throughput (during forwarding) of the bridge increased from `3.5`Mpps (with 64byte packets) to `~11.5`Mpps (with XDP and the `redirect_map` changes proposed in the PR https://github.com/polycube-network/polycube/pull/52.
> Improve simplebridge data plane performance

- AUTHORS
- src/services/pcn-router/src/Ports.cpp
When a port is deleted, the ARP table must also be cleaned
> pcn-router: remove arp table entries when deleting a port

- scripts/check-style.py
I moved by mistake the shebang from the first line, so the script is not working now.
> scripts/checkstyle: move shebang to first line

- src/services/pcn-iptables/src/Chain.cpp
- src/services/pcn-iptables/src/ChainStats.cpp
- src/services/pcn-iptables/src/Iptables.cpp
- src/services/pcn-iptables/src/Iptables.h
- src/services/pcn-iptables/src/SessionTable.cpp
- src/services/pcn-iptables/src/modules/Program.cpp
delete is not needed if erase is called.
this PR replaces also some pointers with smart pointers this allows a better memory handling, avoiding some racing condition.
> pcn-iptables: remove useless delete and use shared_ptr

- src/services/pcn-firewall/src/ChainRule.cpp
This PR fixes a bad initialization of id in default rules statistics.
> pcn-firewall: fix id initialize for default rule

- src/services/pcn-loadbalancer-dsr/src/Lbdsr.cpp
- src/services/pcn-loadbalancer-dsr/src/Lbdsr.h
- src/services/pcn-loadbalancer-dsr/src/Ports.cpp
```
$polycubectl lbdsr lb1 ports add frontend-port type=FRONTEND
Port frontend-port does not exist
```
port creation was failing due to a bad port access in the code.
passing directly the index of the created port to `setFrontendPort()` solves the issue.
> pcn-lbdsr: fix ports creation

- src/libs/polycube/include/polycube/services/base_cube.h
- src/libs/polycube/src/base_cube.cpp
- src/libs/polycube/src/transparent_cube.cpp
Remove some dead code related to packet in functionality in the base cube
class
> libpolycube: remove dead code in cube

- Documentation/components/k8s/pcn-kubernetes.rst
- tests/vagrant/.gitignore
- tests/vagrant/README.md
- tests/vagrant/pcn-k8s/README.md
- tests/vagrant/pcn-k8s/Vagrantfile
This makes the pcn-k8s setup hassle free and help for quick setup with kubeadm and joining the nodes. With just a single command.
> PCN-K8S vagrant setup and documentation update

- Documentation/components/k8s/pcn-kubernetes.rst
URL for Vagrantfile has been corrected to 
`https://raw.githubusercontent.com/polycube-network/polycube/master/tests/vagrant/pcn-k8s/Vagrantfile`
> Correction to the Vagrantfile href

- scripts/install.sh
`pcn-iptables` was not working when run inside docker.
This PR should fix the issue adding some missing dependencies.
> pcn-iptables: fix install.sh to make docker image work

- scripts/install.sh
avoid the error message when pcn-iptables try to unload conntrack module if not needed/required.
> pcn-iptables: fix lsmod error message in docker

- src/polycubectl/harcodedhelp.go
fix for https://github.com/polycube-network/polycube/issues/88.
> polycubectl: fix help for services

- src/libs/polycube/include/polycube/services/base_cube.h
- src/libs/polycube/include/polycube/services/cube.h
- src/libs/polycube/include/polycube/services/cube_factory.h
- src/libs/polycube/src/base_cube.cpp
- src/libs/polycube/src/transparent_cube.cpp
- src/polycubed/src/base_cube.cpp
- src/polycubed/src/base_cube.h
- src/polycubed/src/cube_factory_impl.cpp
- src/polycubed/src/cube_factory_impl.h
after 5a3e91ea90a2 ("implement base datamodel handling in polycubed") the
functionality to change the logging level of a cube was broken.  This because
the logging level was only being changed in the datapath but the control plane
logger (the actual logger that prints it to the terminal) wasn't being updated,
as a result some datapath logs messages were being lost.
This commit creates a new callback that is passed to the framework so when
the logging level is changed the cube is notified and it can update its logger.
Fixes: 5a3e91ea90a2 ("implement base datamodel handling in polycubed")
> fix logging in services

- src/polycubectl/completion/polycubectl.sh
Fix bug that make it unusable.
> polycubectl: fix autocompletion

- src/polycubed/src/server/Resources/Body/ListResource.cpp
- src/polycubed/src/server/Resources/Body/ListResource.h
- src/polycubed/src/server/Resources/Body/ParentResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
The validation code for the list was not testing all the elements of the list,
it instead was testing the list as a container.  Due to this complex commands
issued with a rest client were failing, for instance:
```
curl -L -X POST --data '{"name":"hw0","ports":[{"name":"pippo"}]}' \
"http://localhost:9000/polycube/v1/helloworld/hw0/"
curl -L -X POST --data \
'[{"name":"toveth1", "peer":"veth1"}, {"name":"toveth2", "peer":"veth2"}]' \
"http://localhost:9000/polycube/v1/helloworld/hw0/ports/
```
This commit implements a new logic that tests all the elements in a list, also
a new logic fill the keys in json body of a list request is added as well.
This failure was unnoticed because polycubectl does not allow to perform such
complex operations in a single command.
> polycubed: fix list validation

- src/polycubed/src/server/Resources/Body/ListResource.cpp
- src/polycubed/src/server/Resources/Body/ListResource.h
- src/polycubed/src/server/Resources/Body/ParentResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
- src/services/pcn-k8sfilter/datamodel/k8sfilter.yang
- src/services/pcn-k8switch/src/K8switch.cpp
- src/services/pcn-k8switch/src/K8switch.h
pcn-k8s was broken in few places:
- List validation was wrong and hence it was not possible to create a cube with the ports using a rest client
- k8switch had a bad logic to init the cube on construction time
- k8sfilter had a problem that prevented the creation of ports on this.
> Fix pcn k8s

- src/polycubed/src/cube.cpp
A port is first created and then the peer is configured if needed, if something
goes wrong while setting the peer, remove the created port.
> polycubed: remove port when error setting peer

- src/libs/polycube/include/polycube/services/base_cube.h
- src/libs/polycube/src/base_cube.cpp
get_type() was returning a local variable that was never set, so it always
returned CubeType::TC, this causes a performance degradation in pcn-iptables
because the fib_lookup kernel feature was never used.
> libpolycube: fix cube get type

- src/polycubed/src/server/Resources/Endpoint/ListResource.cpp
List autocompletion was partially broken because a look up with the wrong key
name was done.
This commit also adds some logic to avoid suggesting the "add", "del", "show"
commands when in the middle of a list completion. ex:
polycubectl cube_name complex_list key1 <tab>:  suggest list of key2 for
elements that also matchs key1.
> polycubed: fix list autocompletion

- src/polycubed/src/polycubed.cpp
When SIGINT was received at initialization time there was segfault because
the handler tried to delete the core and rest server that were not allocated
yet.  This commit adds a check to be sure that core and rest server are
allocated when the shutdown handler is invoked.
Solve: https://github.com/polycube-network/polycube/issues/49
> polycubed: fix segfault on init

- src/polycubed/src/base_cube.cpp
- src/polycubed/src/base_model.cpp
- src/polycubed/src/base_model.h
- src/polycubed/src/server/Resources/Data/BaseModel/ConcreteFactory.cpp
- src/polycubed/src/server/Resources/Endpoint/Service.cpp
- src/polycubed/src/server/Resources/Endpoint/Service.h
- src/polycubed/src/server/Validators/InSetValidator.cpp
- src/services/datamodel-common/polycube-base.yang
There is an ongoing work to implement a /cubes/ api that will allow to create
a list of cubes with a single request.  In order to support that operation
there should be a service field that indicates the service type of the cube.
This commit adds the service to be base datamodel and updates polycubed to
support it.
> add service to base datamodel

- src/polycubed/src/server/Resources/Body/ChoiceResource.cpp
- src/polycubed/src/server/Resources/Body/ChoiceResource.h
- src/polycubed/src/server/Resources/Body/LeafListResource.cpp
- src/polycubed/src/server/Resources/Body/LeafListResource.h
- src/polycubed/src/server/Resources/Body/LeafResource.cpp
- src/polycubed/src/server/Resources/Body/LeafResource.h
- src/polycubed/src/server/Resources/Body/ListResource.cpp
- src/polycubed/src/server/Resources/Body/ListResource.h
- src/polycubed/src/server/Resources/Body/ParentResource.cpp
- src/polycubed/src/server/Resources/Body/ParentResource.h
- src/polycubed/src/server/Resources/Body/Resource.h
- src/polycubed/src/server/Resources/Endpoint/LeafResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ListResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
- src/polycubed/src/server/Resources/Endpoint/Service.cpp
polycubed fills the default elements on a request if they are missing, this
guarantees that the default elements are always set when the request arrives to
the service implementation, hence the developer has not to take care of it.
When an update (PATCH) request is done those fields should not be set, because
their value will be modified even if the client wanted to update other elements.
> polycubed: set missing default elements only at initialization time

- src/polycubed/src/server/Resources/Body/ChoiceResource.cpp
- src/polycubed/src/server/Resources/Body/ChoiceResource.h
- src/polycubed/src/server/Resources/Body/LeafListResource.cpp
- src/polycubed/src/server/Resources/Body/LeafListResource.h
- src/polycubed/src/server/Resources/Body/LeafResource.cpp
- src/polycubed/src/server/Resources/Body/LeafResource.h
- src/polycubed/src/server/Resources/Body/ListResource.cpp
- src/polycubed/src/server/Resources/Body/ListResource.h
- src/polycubed/src/server/Resources/Body/ParentResource.cpp
- src/polycubed/src/server/Resources/Body/ParentResource.h
- src/polycubed/src/server/Resources/Body/Resource.h
- src/polycubed/src/server/Resources/Endpoint/LeafResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ListResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
- src/polycubed/src/server/Resources/Endpoint/Service.cpp
- src/services/pcn-k8switch/datamodel/k8switch.yang
- src/services/pcn-k8switch/src/Ports.cpp
- src/services/pcn-k8switch/src/Ports.h
- src/services/pcn-k8switch/src/api/K8switchApi.cpp
- src/services/pcn-k8switch/src/api/K8switchApi.h
- src/services/pcn-k8switch/src/api/K8switchApiImpl.cpp
- src/services/pcn-k8switch/src/api/K8switchApiImpl.h
- src/services/pcn-k8switch/src/interface/PortsInterface.h
The type attribute in the ports is meant to be only set at creation time.
Use the init-only-config flag on this and remove all the update code for it.
Note: merge after https://github.com/polycube-network/polycube/pull/116.
> add init only config to k8switch ports

- src/polycubed/src/server/Resources/Body/ListResource.cpp
- src/polycubed/src/server/Resources/Body/ListResource.h
- src/polycubed/src/server/Resources/Body/ParentResource.cpp
The logic to set default elements in a list was broken as it was trying
to fill the elements as if the list were a container.
This commit reworks the logic to fill default elements, in a list they
are filled only if there are children in the request.
> polycubed: fix issue with lists and default elements

- src/polycubed/src/extiface.cpp
- src/polycubed/src/extiface.h
- src/polycubed/src/transparent_cube.cpp
A transparent cube can be attached to a standard cube's port or to a netdev,
the conversion to json was failing to show it when the cube was attached to a
netdev.
> polycubed: show parent when attached to a netdev

- src/polycubed/src/netlink.cpp
- src/polycubed/src/netlink.h
- src/services/pcn-iptables/src/Iptables.cpp
- src/services/pcn-iptables/src/Iptables.h
- src/services/pcn-iptables/src/modules/ChainSelector.cpp
Socket replacement:
Replacement of the libnl library socket with a raw socket; because in this way it is possible to receive netlink notifications even from the network namespaces.
Added new netlink events:
LINK_ADDED, ROUTE_ADDED, ROUTE_DELETED, NEW_ADDRESS
Removed netlink event ALL (notify_all):
Having a notification without a type is considered not very useful
> Netlink change: Namespace support and event extension

- tests/.gitignore
- tests/helpers_tests.bash
- tests/run-tests-iptables.sh
- tests/run-tests.sh
This commit introduces support for checking services to be
loaded before starting the tests.
From d8d280cd96a49ec4b6706e9ed3eef32c127c108f commit "Added new REST API and validation code", rest server is started [1] before services are loaded.
This introduces the possibility services are not yet loaded when polycubed is up and responsive and can cause tests to fail.
[1] https://github.com/polycube-network/polycube/blob/master/src/polycubed/src/polycubed.cpp#L276
> tests: check for services to be loaded before starting test

- src/polycubed/src/netlink.cpp
select() updates the timeout structure, so if this is not intialized it is
going to be 0 at some point and then create a busy wait loop, using 100% of a
cpu core.
This commit moves the assignent of the timeout structure to its original
location and adds the comment that was removed by mistake.
> polycubed: fix busy wait in netlink socket

- Documentation/polycubectl/polycubectl.rst
- src/polycubectl/aliases.go
- src/polycubectl/cliargs/cliargs.go
- src/polycubed/src/rest_server.cpp
- src/polycubed/src/rest_server.h
- src/polycubed/src/server/Resources/Endpoint/Service.cpp
- src/polycubed/src/server/Resources/Endpoint/Service.h
This PR adds two features to make the configuration of polycube more user friendly.
- a new /cupes/ api is created in polycubed, this allows to create multiple cubes at the time with a single request. This can be used to load the full configuration of a network topology.
- the CLI has been extended to support reading complex configurations from the command line and from files. For instance a full topology can be deployed by `polycubectl  cubes add < my_network.yaml`. This feature is available to all commands.
> Add feature loadtopology

- Documentation/developers/hints.rst
This PR adds documentation about how to profiling `polycubed` with `valgrind`.
> docs: add instructions to run valgrind

- src/components/iptables/README.md
Update pcn-iptables install instructions.
#138
> pcn-iptables: update install instructions

- src/services/pcn-nat/src/Nat_dp_common.c
- src/services/pcn-nat/src/NattingTable.h
ensure st_k and st_v structs are aligned, using `__attribute__((packed))`.
> pcn-nat: fix natting-tables show

- src/services/pcn-iptables/src/Chain.h
- src/services/pcn-iptables/src/Utils.cpp
- src/services/pcn-iptables/src/datapaths/Iptables_Horus_dp.c
- src/services/pcn-iptables/src/defines.h
- src/services/pcn-iptables/src/modules/Horus.cpp
- avoid incompatibility with conntrack rules
- increase horus max size
- use attribute packed to avoid memory alignment issues
> pcn-iptables: fix horus module

- src/polycubed/src/port.cpp
- src/polycubed/src/port.h
A dead lock is possible when a transparent cube is added to a port
and there is a packetout operation at the same time.
If port1 and port2 are connected, a packetout operation is going
on port1 and a cube is attached to port2
```
Thread1:                          | Thread2:
port1->send_packet_out()          | port2->add_cube()
lock(port1)                     |   lock(port2)
...                             |   ...
port2->get_index()              |   port1->set_next_index()
lock(port2)                   |     lock(port1)
```  
The main cause of this is that send_packet_out() uses get_index() that
internally uses a lock.  This commit modifies get_index() so it doesn't
> polycubed: fix packet out deadlock when attaching transparent cubes

- tests/vagrant/pcn-k8s/Vagrantfile
Two small fixes for the k8s vagrant file:
- the url of the yaml templates was missing the branch name
- in the new releases of kubeadm the configuration file is at
/var/lib/kubelet/kubeadm-flags.env
> Vagrant: fix bad url and file name

- src/services/pcn-firewall/src/defines.h
- src/services/pcn-iptables/src/defines.h
wrong const type was committed by mistake during porting of HORUS functionalities.
This PR fixes this issue.
> pcn-iptables: fix wrong const type

- src/libs/polycube/include/polycube/services/cube_iface.h
- src/libs/polycube/include/polycube/services/port.h
- src/libs/polycube/include/polycube/services/port_iface.h
- src/libs/polycube/include/polycube/services/transparent_cube.h
- src/libs/polycube/include/polycube/services/types.h
- src/libs/polycube/src/port.cpp
- src/libs/polycube/src/transparent_cube.cpp
- src/polycubed/src/extiface.cpp
- src/polycubed/src/extiface.h
- src/polycubed/src/peer_iface.h
- src/polycubed/src/polycubed_core.cpp
- src/polycubed/src/polycubed_core.h
- src/polycubed/src/port.cpp
- src/polycubed/src/port.h
- src/polycubed/src/server/Resources/Data/Lib/ConcreteFactory.cpp
- src/polycubed/src/transparent_cube.cpp
- src/polycubed/src/transparent_cube.h
- src/polycubed/src/utils/netlink.cpp
- src/polycubed/src/utils/netlink.h
- src/polycubed/src/utils/veth.cpp
- src/services/pcn-nat/src/Nat.cpp
- src/services/pcn-nat/src/Nat.h
- src/services/pcn-router/src/Ports.cpp
- src/services/pcn-router/src/Ports.h
This PR adds:
A. The methods to align a port or a transparent cube with a netdev, when they are connected to each other.
The methods added are:
1) `subscribe_parameter(caller, parameter, callback function)` = subscribe the port or the transparent cube to the change of the parameter. If the netdev changes that parameter it is called the callback function.
2) `unsubscribe_parameter(caller, parameter)` = cancel the subscription of the port or the transparent cube by changing the parameter.
3) `set_parameter(parameter, value)` = update the parameter on the netdev with the new value.
B. The methods to align the parameters between a transparent cube and a port, when the cube is attached to the port.
The methods in this case are:
4) `subscribe_parent_parameter(parameter, callback function)`.
5) …
>  Alignment between port/transparent_cube and netdev (when they are connected)

- src/CMakeLists.txt
- src/polycubed/src/base_cube.cpp
The 0.7.0 version we're using is not compatible with kernels 5.0, update
this to a 0.10.0 that is compatible.
Note: this should be merged while https://github.com/polycube-network/bcc/tree/polycube is updated to https://github.com/polycube-network/bcc/tree/polycube_on_v0.10.0
> update to new bcc

- src/polycubed/src/port.cpp
- src/polycubed/src/port.h
- src/polycubed/src/utils/netlink.h
- src/services/pcn-router/src/Ports.cpp
Some fixes for the align interfaces:
- use port_mutex instead of a new one
- do not call a function to update the port ip in router
- call callbacks in netlink without helding a lock
Fixes: 48bf03919f91 ("Merge pull request #158 from francescomessina/align_ifaces")
> fix align interfaces logic

- Documentation/polycubed/polycubed.rst
- src/polycubed/src/CMakeLists.txt
- src/polycubed/src/config.cpp
- src/polycubed/src/config.h
- src/polycubed/src/cubes_dump.cpp
- src/polycubed/src/cubes_dump.h
- src/polycubed/src/peer_iface.cpp
- src/polycubed/src/peer_iface.h
- src/polycubed/src/polycubed.cpp
- src/polycubed/src/polycubed_core.cpp
- src/polycubed/src/polycubed_core.h
- src/polycubed/src/rest_server.cpp
- src/polycubed/src/rest_server.h
- src/polycubed/src/server/Resources/Body/ListKey.h
- src/polycubed/src/server/Resources/Endpoint/LeafResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ListResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ParentResource.h
- src/polycubed/src/server/Resources/Endpoint/Resource.cpp
- src/polycubed/src/server/Resources/Endpoint/Resource.h
- src/polycubed/src/server/Resources/Endpoint/Service.cpp
- src/polycubed/src/server/Resources/Endpoint/Service.h
This feature allows to load a topology from file at startup, either from the default folder or from a user selected file (ex. polycubed --cubes-dump ~/Desktop/cubes.yaml), keeping the whole configuration in memory.
After each modification in any of the topology of the cube, the configuration in memory is updated and another thread saves it to file updating it too.
It is possible to start the daemon with an empty topology by using the flag --cubes-init: if the file contains a topology, at the first update it is overwritten.
It is possible to start the daemon without the dumping to file functionality by using the flag --cubes-nodump.
> load old topology at startup and save each modification to file

- src/polycubed/src/config.cpp
- src/polycubed/src/polycubed.cpp
Set to false the Config::cubes_dump_file_flag before cli arguments parsing
and load topology only if requested.
> fix pr/save_load_topology bug

- src/polycubed/src/config.cpp
- src/polycubed/src/server/Resources/Endpoint/LeafResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ListResource.cpp
- src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
- src/polycubed/src/server/Resources/Endpoint/Service.cpp
Commented default cubes-dump-file configuration to avoid affecting
parameters validation and removed useless variable assignment.
Check if the dump is enabled with the variable set in config.cpp
instead of checking if CubesDump instance is created or not.
> fix polycubed.conf default configuration and cubes dump bug

- src/polycubed/src/polycubed.cpp
When running polycubed as normal user, the printed error is misleading, as it appears that polycubed cannot open the log file.
Signed-off-by: Fulvio Risso <fulvio.risso@polito.it>
> Fixing misleading message when polycubed is not executed as root

- src/polycubed/src/polycubed_core.cpp
If cubes_dump is not initialized properly, it may happen that a wrong memory area is accessed while this is dereference below.
This causes random failures like deadlocks, segmentation faults or even a "invalid argument" message.
> polycubed_core: initializes the cubes_dump_ variable to null

- scripts/install.sh
Given the commits on my previous PR on this matter, I removed that PR and opened a new one.
In this case I kept everything as is, except that I added a new flag in install script so that you can (optionally) also update the source code in the repository. This enables to use this install script against with the most updated source code, while keeping the current behaviour of the script (i.e., install only) unchanged.
This should solve the concerts I've got on the previous PR.
Signed-off-by: Fulvio Risso <fulvio.risso@polito.it>
> Added option to update source code in install script

- src/libs/polycube/include/polycube/services/utils.h
- src/libs/polycube/src/utils.cpp
- src/polycubed/src/utils/netlink.cpp
- src/services/pcn-bridge/src/Fdb.cpp
- src/services/pcn-bridge/src/FdbEntry.cpp
- src/services/pcn-bridge/src/Stp.cpp
- src/services/pcn-ddosmitigator/src/BlacklistDst.cpp
- src/services/pcn-ddosmitigator/src/BlacklistSrc.cpp
- src/services/pcn-ddosmitigator/src/Ddosmitigator.cpp
- src/services/pcn-firewall/src/Firewall.cpp
- src/services/pcn-firewall/src/defines.h
- src/services/pcn-firewall/src/modules/IpLookup.cpp
- src/services/pcn-iptables/src/Iptables.cpp
- src/services/pcn-iptables/src/defines.h
- src/services/pcn-iptables/src/modules/ChainSelector.cpp
- src/services/pcn-iptables/src/modules/IpLookup.cpp
- src/services/pcn-k8switch/src/K8switch.cpp
- src/services/pcn-k8switch/src/Service.cpp
- src/services/pcn-loadbalancer-dsr/src/Backend.cpp
- src/services/pcn-loadbalancer-rp/src/Service.cpp
- src/services/pcn-loadbalancer-rp/src/SrcIpRewrite.cpp
- src/services/pcn-nat/src/IpAddr.h
- src/services/pcn-nat/src/Nat.cpp
- src/services/pcn-nat/src/RuleMasquerade.cpp
- src/services/pcn-pbforwarder/src/Rules.cpp
- src/services/pcn-router/src/Ports.cpp
- src/services/pcn-router/src/Router.cpp
- src/services/pcn-simplebridge/src/Fdb.cpp
- src/services/pcn-simplebridge/src/FdbEntry.cpp
- src/services/pcn-simplebridge/src/Ports.cpp
-ip_string_to_be_uint => ip_string_to_nbo_uint
-be_uint_to_ip_string => nbo_uint_to_ip_string
-mac_string_to_be_uint => mac_string_to_nbo_uint
-be_uint_to_mac_string => nbo_uint_to_mac_string
Where "nbo" means network byte order
> libpolycube: rename functions in the utils library

- src/polycubectl/help.go
- src/services/pcn-bridge/src/Fdb.cpp
- src/services/pcn-iptables/datamodel/iptables.yang
Added a void line at the end when printing the help on screen.
Updated the description of iptables services (it was void before) and adding standard metadata.
> Print cleanup

- scripts/install.sh
The GPG key for the liberouter repository has expired, so the Polycube install script does not work anymore. While waiting the liberouter maintainers to update the key, this PR introduces a workaround in the Polycube install script so that our project compiles anyway. The workaround is simply a download of the required dependencies and the manual install through apt.
> Removing the liberouter repo because the GPG key has expired

- src/polycubed/src/extiface.cpp
When a transparent service is connected to a port it asks for the name of the cube to which it has been connected. 
In the case in which a transparent service is attached to a netdev the name of the netdev is returned.
This PR adds a new parameter to the extiface class, which implements this behavior.
> libpolycube: add a new parameter to the get_parameter in the extiface

- Documentation/developers/controlplane.rst
- Documentation/developers/datapath.rst
- Documentation/developers/debugging.rst
- Documentation/developers/index.rst
- Documentation/polycubectl/polycubectl.rst
This PR adds a new Debugging section into Polycube Developer Guide:
"Debugging and logging in the data plane" and "Debugging and logging in the control plane" sections have been brought together in a single document; this document explains the use of polycube logging features and shows how to filter the log messages produced by the polycubed-daemon and running services.
> Adding Debugging section into Polycube Developers Guide

- src/polycubed/src/transparent_cube_tc.cpp
some caller like pcn_pkt_controller_with_metadata_stack may set this flag. pass_to_stack flag was carried by cb[0] in the first MSB in the last 16 bits (0x8000) and this flag will be used to decide if the packet should be sent to stack for further processing or dropped. 
this fix issue #210
> keep the pass_to_stack flag in skb 

- Documentation/components/k8s/pcn-kubernetes.rst
- src/components/k8s/examples/echoserver_nodeport.yaml
- src/components/k8s/pcn-k8s.yaml
- src/components/k8s/standalone_etcd.yaml
The newest version of Kubernetes, 1.16, has dropped support for resources that use `apiVersion: extensions/v1beta1`: this made `pcn-k8s` incompatible with Kubernetes 1.16, as some of its resources rely on that version.
This PR fixes this compatibility issue and updates documentation to specify the minimum Kubernetes version supported by pcn-k8s.
> pcn-k8s: Fix pcn-k8s compatibility issue with 1.16

- AUTHORS
- Documentation/developers/index.rst
- Documentation/developers/profiler.rst
- scripts/profiler_parser.py
- src/libs/polycube/include/polycube/profiler.h
- src/polycubed/src/controller.cpp
Pull request of the profiling framework developed as a header class library.
​
The developed framework has been used to measure time taken by Polycubed to start.
```bash
Old include in controller.cpp line 98 => `#include <linux/kernel.h> `
​
=============================================================================================================================================
||FROM                                         |TO                                           |TIME(ns)                                     ||
=============================================================================================================================================
||Start                                        |Start+1                                      |145 …
```
> pr/profiling - Polycube Benchmarking Framework

- Documentation/installation.rst
This PR updates the list of commands needed to install libyang-dev present in the Polycube manual installation guide to align them with those present in the automatic installation script.
> Updating libyang-dev manual installation commands

- Documentation/developers/debugging.rst
- src/CMakeLists.txt
- src/libs/polycube/include/polycube/services/utils.h
- src/libs/polycube/src/base_cube.cpp
- src/libs/polycube/src/utils.cpp
- src/polycubed/src/CMakeLists.txt
This PR removes all the references to polycube-tools from source code and documentation.
> Removing references to polycube-tools

- src/libs/polycube/include/polycube/services/cube_iface.h
- src/libs/polycube/include/polycube/services/transparent_cube.h
- src/libs/polycube/src/transparent_cube.cpp
- src/polycubed/src/transparent_cube.cpp
- src/polycubed/src/transparent_cube.h
- src/services/pcn-ddosmitigator/src/Ddosmitigator.cpp
- src/services/pcn-ddosmitigator/src/Ddosmitigator.h
- src/services/pcn-firewall/src/Firewall.cpp
- src/services/pcn-firewall/src/Firewall.h
- src/services/pcn-nat/src/Nat.cpp
- src/services/pcn-nat/src/Nat.h
- src/services/pcn-synflood/src/Synflood.cpp
- src/services/pcn-synflood/src/Synflood.h
- src/services/pcn-transparent-helloworld/src/Transparenthelloworld.cpp
- src/services/pcn-transparent-helloworld/src/Transparenthelloworld.h
As "Sense" is not the correct term to indicate the direction of a packet that arrives to a service port, this PR renames it as Direction.
> Refactoring service::Sense to service::Direction

- Documentation/components/k8s/developers.rst
- add extra line to make literal code block display appropriately
- fix the docker build parameter, pcn-k8s should be passed to docker as argument
instead of environment
> fix pcn-k8s docker build document

- CI/JenkinsfileTestCleanInstance
- Dockerfile
- src/services/pcn-nat/test/test_tcp_snat.sh
- src/services/pcn-pbforwarder/test/test2_10.sh
- tests/helpers_tests.bash
Docker base image is now built only triggered by a `cron` at 2:00 am (everyday) to reduce the building time of the pipeline.
Mounting volumes of the polycubed image have been changed:
- `/proc` is now mounted under `/host/proc` to have a complete visibility of the namespaces created outside of the container.
Solving iptables tests:
Docker manipulates the iptables policy of the node during his installation and this makes the kernel drop the packets forwarded between different network namespaces; to solve this, `sudo iptables -P FORWARD ACCEPT` must be run on the host before running tests in order avoid the kernel drops packets.
> Fixing jenkins pipeline & tests

- Dockerfile_base_image
- scripts/pre-requirements.sh
the docker image is built against the /tmp/polycube directory which is copied from the latest source code, but in the based image the /tmp/polycube is already existing. In the case the based image is not the latest code then the docker image doesn't contains the latest code. 
This PR make a clean sandbox before copying and building the docker image against the source code, otherwise the docker image could be built against the old sandbox left-over in the base image. Another way to do that is to clean the base image /tmp/polycube directory but anyway make a clean sandbox is always a good habit without any assumption.
> fix docker file issue 

- CI/JenkinsfileTestCleanInstance
- CI/clean_slave.sh
This PR adds a Stage that clears the working directory of the slaves before building the docker images
and looks for non-deleted namespaces left by tests and delete them.
> Adding Clean Directory and Checkout + after-tests namespaces cleaning

- tests/converter/to_junit.py
- tests/helpers_tests.bash
This PR enhances the collection of standard output while running CI tests. So far, stdout was kept only in case of FAILURE making hard to detect false negatives.
> Add standard output messages for successful tests

- src/libs/polycube/include/polycube/services/utils.h
- src/libs/polycube/src/utils.cpp
- src/services/pcn-nat/src/Nat.cpp
- src/services/pcn-nat/src/Nat_dp.c
- src/services/pcn-nat/test/test_tcp_masq.sh
This pull request will fix NAT service.
We need to investigate if the problem persists for future transparent services.
> Fixed NAT service and modified utils function

- src/services/pcn-router/src/Router.cpp
If getIP returns an empty value it means that you have a port with no IP address so you do not need to call remove_local_route
Fixes #243
> Solved bug reported in issue #243

- src/polycubectl/config/config.go
polycubectl creates a folder without traverse permission to contain the config file.
This causes the subsequent file generation to fail.
This PR fixes the problem.
> Generate polycubectl config directory with traverse permission

- src/polycubed/src/extiface.cpp
- src/polycubed/src/extiface.h
- src/polycubed/src/peer_iface.cpp
- src/polycubed/src/peer_iface.h
- src/polycubed/src/polycubed_core.cpp
- src/polycubed/src/polycubed_core.h
- src/polycubed/src/rest_server.cpp
- src/polycubed/src/rest_server.h
- src/polycubed/src/transparent_cube.cpp
- src/polycubed/src/transparent_cube.h
- tests/transparent_services/test_service_chain.sh
When attach multiple cubes to one interface with "position=last", "before=xxx", "after=xxx", system crashes. This PR fixes the crashing issue and add a CLI to check the cubes attaches to a interface given a name.
> fix polycubed crash & add a CLI to check the cubes given a interface

- src/services/pcn-firewall/src/Firewall.cpp
Adjust the init order when creating firewall cube object so the parameter passed
by user can be populated, the will also avoid the crash due to object reference
before object initialization.
issue #184
> fix firewall creation fails issue 

- scripts/man.sh
This bash based script allows to show services documentation in a whiptail dialog.
> A new elegant whiptail based documentation script for polycube

- src/polycubectl/prettyprint.go
This prevents the number-like name being formatted as floating when using polycubectl to dump the cube information.
Refer to https://github.com/polycube-network/polycube/issues/16
> bypass the data format if the data is a string type

- src/libs/polycube/CMakeLists.txt
- src/libs/polycube/include/polycube/services/base_cube.h
- src/libs/polycube/include/polycube/services/cube_iface.h
- src/libs/polycube/src/base_cube.cpp
- src/polycubed/src/base_cube.cpp
- src/polycubed/src/base_cube.h
Thanks to the changes done [here](https://github.com/polycube-network/bcc/pull/2), the BaseCube class can now get the description about the instantiated eBPF maps through the `TableDesc` class.
This PR adds all the methods needed to retrieve the TableDesc objects of the eBPF maps used in the ingress and egress programs of a Cube.
> Exporting TableDesc object to the BaseCube

- src/polycubed/src/polycubed.cpp
- src/polycubed/src/rest_server.cpp
- src/polycubed/src/rest_server.h
Currently the Pistache `maxPayload`  option has not been managed in the initialization of the Pistache server, so the HTTP requests with a payload size bigger than the default Pistache' setting produce a `Request exceeded maximum buffer size` response error message, with strange behaviors on the subsequent HTTP requests.
This PR adds the `maxPayload` option in the initialization of the Pistache server and set it to a default value of [`64KB`](https://github.com/polycube-network/polycube/blob/473f505c4f252e98473ea97a83bf9a17fd5166e1/src/polycubed/src/rest_server.h#L56).
The value of `maxPayload` is then customized in the rest server setup with a value of [`1MB`](https://github.com/polycube-network/polycube/blob/473f505c4f252e98473ea97a83bf9a17fd5166e1/src/polycubed/src/polycubed.cpp#L277).
> Implementing maxPayload Pistache option personalization

- src/libs/polycube/include/polycube/services/cube.h
- src/libs/polycube/include/polycube/services/cube_factory.h
- src/libs/polycube/src/transparent_cube.cpp
- src/polycubed/src/base_cube.cpp
- src/polycubed/src/controller.cpp
- src/polycubed/src/cube_tc.cpp
- src/polycubed/src/cube_xdp.cpp
- src/polycubed/src/extiface_xdp.cpp
- src/polycubed/src/transparent_cube_tc.cpp
- src/polycubed/src/transparent_cube_xdp.cpp
This PR adds support to store the traffic class of a packet in the packet metadata of the data plane.
The value is represented as a `uint32` field in `struct pkt_metadata`, and is propagated to all programs that compose the dataplane pipeline.
Traffic class is also made available among the metadata of the `packet_in()` method in the control plane of services.
> Add traffic class to packet metadata

- src/services/pcn-packetcapture/client/packetcapture.py
this pr makes the following changes:
- renamed folder "Packetcapture_Client" to "client"
- renamed "client.py" to "packetcapture.py"
- fixed buffer syncronization problem when producing the dump from the client (malformed packet)
> Changed packetcapture client name and fixed the buffer synchronization

- src/libs/polycube/include/.gitignore
- src/services/pcn-router/src/Ports.cpp
- src/services/pcn-router/src/PortsSecondaryip.cpp
- src/services/pcn-router/src/Router.cpp
This PR fixes some bugs of the router service.
- There was an error when setting the secondary ip address during port initialization.
To replicate the problem try to create a router posting this json:
```
{
"ports": [
{
"name": "p1",
"ip": "10.0.0.1/24",
"secondaryip": [
{"ip": "10.0.1.1/24"}
] 
}
]
}
```
to `http://localhost:9000/polycube/v1/router/r1`, the creation of the cube will fail.
Fixed with commit 079dbf10903aa01870d289a460ed872895d3c377.
- When adding a /32 address to an interface a local network was also added, this caused problems when trying to reach that ip.
To replicate:
```
polycubectl router add r1
polycubectl r1 ports add lo ip=172.99.0.1/32
```
connect the router to a namespace and try to ping 172.99.0.1 (you need to add a route to this address in the namespace), the …
> Router bug fixes

- scripts/pre-requirements.sh
This commit fixes a previous PR I made where, to check the OS versions, I used `bc` from command line assuming that it existed. It turned out that this caused problem, so now I am proposing to add this command in the installation process
> Fix Missing `bc` command

- src/services/pcn-dynmon/src/Dynmon.cpp
- src/services/pcn-dynmon/src/MapExtractor.cpp
- src/services/pcn-dynmon/test/test2.sh
- src/services/pcn-dynmon/test/test_map_extraction.json
This PR addresses the 2nd point discussed in polycube-network#291.
It has been introduced the key extraction, meaning that if the bpf map is a
key-value type one, not only the value is exported, but also the associated key.
Still, for map-in-map types there is not full support yet, due to many problem related to
the map info retrieval.
> Dynmon enhancement - Key export feature

- src/polycubed/src/server/Resources/Body/ParentResource.cpp
As indicated in [RFC6020](https://tools.ietf.org/html/rfc6020#section-3.1), a Yang container is mandatory only when the "presence" statement is NOT present and it has at least one mandatory node as a child.
This PR fixes the return value of the `ParentResource::IsMandatory()` which currently returns `true` when the presence statement is present.
> Fixing ParentResource::IsMandatory return value

- src/services/CMakeLists.txt
This PR aims to update the submodule BCC in Polycube to the latest version
0.14.0, according to our recent updated in https://github.com/polycube-network/bcc/tree/polycube
> Updated BCC submodule to version 0.14.0

- src/services/CMakeLists.txt
Polycube bcc library update according to the latest fix in our BCC library version.
They changed the Cmakelist.txt, which forced the installation path to another directory rather than the one used in Polycube.
> BCC update 0.14.0 with force path fix

- scripts/create_pcn_sourcepack.sh
- scripts/install.sh
This PR introduce a script to create an archive (zip and tar) with all the polycube sources, including submodules. It is possible to choose to make an archive from a branch with a version or from a tag and use the tag for the version.
> Script to create zip and tar of Polycube with submodules

- Documentation/developers/dataplane.rst
- src/polycubed/src/base_cube.cpp
PR to fix name of Polycube helper to retrieve timestamp in Unix Epoch + Doc
Related issue: #277
> fix ebpf timestamping nomenclature

- .github/CODEOWNERS
Federico Parola to be added for the PR reviews as per requested by @frisso 
This list can be further extended.
> Adding Federico Parola for PR review

- src/services/pcn-ddosmitigator/src/Ddosmitigator.cpp
When an address is already present no operation is performed.
Formerly the address was erroneously removed from the ebpf table.
> ddosmitigator: handle insertion of already present address

- src/services/pcn-router/src/Ports.cpp
This PR contains a possible solution to the bug #349 
```
~ polycubectl router add r1                            
~ polycubectl r1 ports p1  
~ polycubectl r1 ports p1 secondaryip add 10.0.0.254/24
You can not add a secondary ip address to a port with no ip address
```
> Solved router bug reported in issue #349

- src/services/pcn-dynmon/src/extractor/MapExtractor.cpp
- src/services/pcn-dynmon/tools/dynmon_injector.py
when deleting entries in PERCPU_HASH map, the bucket was not zero-ed. Thus, following entries using that bucket would have junk values belonging to the previous entry.
> fix PERCPU maps entries deletion and improved injector python script

- src/polycubed/src/cube_xdp.cpp
- src/polycubed/src/transparent_cube_xdp.cpp
There is a bug when reloading a program in the egress path of a XDP cube: XDP egress is emulated with two programs, a TC one to handle packets coming from the stack and a XDP one to handle packets coming from other XDP cubes. This programs should share the same maps in order to behave as one. There is a bug that causes these maps to differ after a reload. This patch fixes the problem.
> Fix map reuse when reloading TC egress program of XDP cubes

- .github/workflows/ci.yml
In the `pull_request` event secrets are not accessible due to security reasons. This causes all PR tests to fail since secrets are needed to send Slack notifications and to push test docker images.
This PR replaces the `pull_request` event with `pull_request_target`. With this event the workflow is executed in the target context, meaning that it executes only the workflow already present in the master, unlike `pull_request` that executes the workflows contained in the PR. This allows to access secrets.
This is only a temporary solution since automatically checking out an unknown PR may still pose some security issues.
> Use pull_request_target event to trigger CI tests

- src/services/pcn-router/src/Ports.cpp
This PR fixes bug #350  
The error was that before deleting the secondaryip, (by calling the `delete_router_ports_secondaryip_by_id` method which calls `delSecondaryip`), the method `read_router_ports_secondaryip_by_id` was called which inside calls `getSecondaryip(ip)`. Here  the case in which a secondaryip was not present was not handled (both because does not exist or because the port has no secondaryip or even the main ip address).
In the proposed solution, the `getSecondaryip` method returns nullptr if it does not find the secondaryip and then in the `read_router_ports_secondaryip_by_id method` an empty `PortsSecondaryipJsonObject` is returned; doing so will call the `delete_router_ports_secondaryip_by_id` (like a normal execution) method which will handle the error displaying it to …
> A possible solution to solve bug #350

- src/services/pcn-nat/src/Nat.cpp
This PR fixes bug #352 
If you reset the rule_ variable (putting it to nullptr) in the delRule method, a subsequent command like ` polycubectl nat1 show` ends up calling the toJsonObject method to construct the JSON to be displayed to the user. Here we have this statement conf.setRule(getRule ()->toJsonObject ()); which, however, calls the toJsonObject() on a nullptr variable which causes the error.
The solution was to leave the deletion of rule_ in the delRule method in such a way as to also delete all the other rules (snat, dnat, port-forwarding) and then do as in the constructor, creating an "empty" rule_.
This solution also works for the case in which no rules have been added to the NAT and a user tries to do ` polycubectl nat1 rule del`.
Here there is an example:
``` …
```
> A possible solution to fix bug #352

- src/polycubed/src/server/Resources/Body/ListKey.cpp
g++-10 requires to explicitly include `stdexcept` when using exceptions.
Fixes #382
> Fix compilation with g++-10

- Documentation/polycubectl/polycubectl.rst
- src/components/k8s/utils/k8sfilter/k8sfilter.go
- src/components/k8s/utils/k8sfilter/k8sfilter_api.go
- src/components/k8s/utils/k8sfirewall/api_firewall.go
- src/components/k8s/utils/k8sfirewall/model_firewall.go
- src/components/k8s/utils/k8switch/k8switch.go
- src/components/k8s/utils/k8switch/k8switch_api.go
- src/polycubectl/help.go
- src/services/datamodel-common/polycube-base.yang
- src/services/pcn-synflood/swagger_api/synflood_swagger
- src/services/pcn-transparent-helloworld/datamodel/transparent-helloworld.yang
This PR solves issue #193 
* The solution was to use the `cli-example` extension defined in polycube-base and if present in the yang of the service, it is printed in a new column.
* Finally for simplicity of visualization I have reduced the description of `loglevel`
> Solved issue #193

- scripts/install.sh
- scripts/pre-requirements.sh
Currently it was added only if OS< 20.04; this is wrong, golang has to be always installed; what's different is that in pre-20.04 you have to add explicitely the package repository.
> Adding golang to the list of packages to be installed

- src/services/pcn-nat/test/examples/example1.sh
- src/services/pcn-nat/test/examples/example2.sh
- src/services/pcn-nat/test/examples/example3.sh
- src/services/pcn-nat/test/examples/example4.sh
Examples were not updated when migrating the NAT to a transparent cube
> Update NAT examples to use transparent version of the nat

- src/services/pcn-loadbalancer-rp/src/Lbrp.cpp
- src/services/pcn-loadbalancer-rp/src/Service.cpp
Hi folks! If we try to delete a service without backends, calling directly Service::removeServiceFromKernelMap will generate an exception, so is needed to call Service::delBackendList (that performs a check on the number of backends and performs the cleanup in the right way) in order to correctly delete a service.
> fixed Lbrp::delService handling of service backends deletion

- src/polycubed/src/cube.cpp
- src/polycubed/src/cube.h
- src/polycubed/src/cube_tc.cpp
- src/polycubed/src/cube_xdp.cpp
The code of the pcn_pkt_redirect() function of standard cubes is dynamically generated to handle redirection to other cubes/interfaces with a switch-case statement.
When there are too many peers however (> 17) this code becomes too big and is rejected by the verfier.
This commit keeps the optimized path for the first peers and adds a fall back table to redirect to other peers.
> Fall back to map lookup when cube's redirection code becomes too big
